region                      = "eu-west-1"
naming_prefix                = "gha"
project_name                = "GitHub Actions"
#role_to_assume              = "arn:aws:iam::092228957173:role/cawe/cawe-developer"
#vpc_id                      = "vpc-01aedb93ed7ee352d"
#subnet_id                   = "subnet-014b384245485fcc5" #needs to be the same az as the dh
security_group_id           = null
associate_public_ip_address = true
root_volume_size_gb = 150
