teams:
  - team_name: "Spaceship"
    team_description: "Spaceship Devops team"
    users:
      - username: João Gonçalves
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Joao.PC.Goncalves@ctw.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Joao.PC.Goncalves@ctw.bmwgroup.com
        QNumber: qxz2o4h
        Email: Joao.PC.Goncalves@ctw.bmwgroup.com
        GitHubUsername: JoaoPCGoncalves

      - username: Francisco Cunha
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Francisco.AC.Cunha@ctw.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Francisco.AC.Cunha@ctw.bmwgroup.com
        QNumber: qxz4tv7
        Email: Francisco.AC.Cunha@ctw.bmwgroup.com
        GitHubUsername: francisco-ac-cunha

      - username: Daniel Costa
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/daniel.jc.costa@bmw.de
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/daniel.jc.costa@bmw.de
        QNumber: qxz13md
        Email: daniel.jc.costa@bmw.de
        GitHubUsername: daniel-jc-costa

      - username: Jose Faria
        GitHubRole: maintainer
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/jose.faria@ctw.bmwgroup.com
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Jose.Faria@ctw.bmwgroup.com
        QNumber: qxz37pf
        Email: jose.faria@ctw.bmwgroup.com
        GitHubUsername: JoseFaria

      - username: Felipe Valim
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Felipe.Valim@ctw.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Felipe.Valim@ctw.bmwgroup.com
        QNumber: qxz44fc
        Email: Felipe.Valim@ctw.bmwgroup.com
        GitHubUsername: felipevalim

      - username: Nuno Dantas
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Nuno.FF.Dantas@ctw.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Nuno.FF.Dantas@ctw.bmwgroup.com
        QNumber: qxz4jjl
        Email: Nuno.FF.Dantas@ctw.bmwgroup.com
        GitHubUsername: nuno-ff-dantas

      - username: Filipe Couto
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Filipe.Couto@ctw.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Filipe.Couto@ctw.bmwgroup.com
        QNumber: qxz4067
        Email: Filipe.Couto@ctw.bmwgroup.com
        GitHubUsername: filipe-couto

      - username: Diogo Costa
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Diogo.Costa@ctw.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Diogo.Costa@ctw.bmwgroup.com
        QNumber: qxz4p7k
        Email: Diogo.Costa@ctw.bmwgroup.com
        GitHubUsername: diogo-costa

      - username: Jonas França
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Jonas.Franca@ctw.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Jonas.Franca@ctw.bmwgroup.com
        QNumber: qxz33ua
        Email: jonas.franca@ctw.bmwgroup.com
        GitHubUsername: JonasFranca

      - username: Michael Knapp
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/michael.km.knapp@bmw.de
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/michael.km.knapp@bmw.de
        QNumber: q479085
        Email: michael.km.knapp@bmw.de
        GitHubUsername: michael-km-knapp

  - team_name: "Spaceship-L2"
    team_description: "Spaceship L2 team"
    users:
      - username: Chirag Makkar
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Chirag.Makkar@partner.bmw.de
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Chirag.Makkar@partner.bmw.de
        QNumber: qxz0gbq
        Email: chirag.makkar@partner.bmw.de
        GitHubUsername: ChiragMakkar

      - username: Abhay Kumar
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/abhay.ka.kumar@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/abhay.ka.kumar@partner.bmwgroup.com
        QNumber: qxz15wh
        Email: abhay.ka.kumar@partner.bmwgroup.com
        GitHubUsername: AbhayKumar

      - username: Prateek Pandey
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/prateek.pandey@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/prateek.pandey@partner.bmwgroup.com
        QNumber: qxz3kde
        Email: prateek.pandey@partner.bmwgroup.com
        GitHubUsername: PrateekPandey

      - username: Sumit Agarwal
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Sumit.Agarwal@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Sumit.Agarwal@partner.bmwgroup.com
        QNumber: qxz3yvn
        Email: Sumit.Agarwal@partner.bmwgroup.com
        GitHubUsername: SumitAgarwal

      - username: Mukesh Joshi
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Mukesh.joshi@partner.bmw.de
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Mukesh.joshi@partner.bmw.de
        QNumber: qxz0v5y
        Email: Mukesh.joshi@partner.bmw.de
        GitHubUsername: MukeshJoshi

      - username: Sourav Raghuvanshi
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Sourav.rb.raghuvanshi@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Sourav.rb.raghuvanshi@partner.bmwgroup.com
        QNumber: qxz2kyb
        Email: Sourav.rb.raghuvanshi@partner.bmwgroup.com
        GitHubUsername: SouravRaghuvanshi

      - username: Prakhar Bhatia
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Prakhar.Bhatia@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Prakhar.Bhatia@partner.bmwgroup.com
        QNumber: qxz3yvq
        Email: Prakhar.Bhatia@partner.bmwgroup.com
        GitHubUsername: PrakharBhatia

      - username: Avni Goyal
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Avni.Goyal@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Avni.Goyal@partner.bmwgroup.com
        QNumber: qxz3yvm
        Email: Avni.Goyal@partner.bmwgroup.com
        GitHubUsername: AvniGoyal

      - username: Nitin Negi
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Nitin.NN.Negi@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Nitin.NN.Negi@partner.bmwgroup.com
        QNumber: qxz3yvs
        Email: Nitin.NN.Negi@partner.bmwgroup.com
        GitHubUsername: NitinNNNegi

      - username: Vaibhav Singhal
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Vaibhav.Singhal@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Vaibhav.Singhal@partner.bmwgroup.com
        QNumber: qxz1w1s
        Email: Vaibhav.Singhal@partner.bmwgroup.com
        GitHubUsername: VaibhavSinghal

      - username: Devendra Sahu
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Devendra.Sahu@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Devendra.Sahu@partner.bmwgroup.com
        QNumber: qxz413x
        Email: Devendra.Sahu@partner.bmwgroup.com
        GitHubUsername: DevendraSahu

      - username: Saurav Srivastava
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/saurav.srivastava@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/saurav.srivastava@partner.bmwgroup.com
        QNumber: qxz3wen
        Email: saurav.srivastava@partner.bmwgroup.com
        GitHubUsername: SauravSrivastava

      - username: Mangi Lal
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/mangi.lal@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/mangi.lal@partner.bmwgroup.com
        QNumber: qxz1tti
        Email: mangi.lal@partner.bmwgroup.com
        GitHubUsername: MangiLal

      - username: Jason Zhong
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Jason.Zhong@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Jason.Zhong@partner.bmwgroup.com
        QNumber: qxz3z5n
        Email: Jason.Zhong@partner.bmwgroup.com
        GitHubUsername: JasonZhong

      - username: Ray Zhang
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Ray.Zhang@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Ray.Zhang@partner.bmwgroup.com
        QNumber: qxz3z5l
        Email: Ray.Zhang@partner.bmwgroup.com
        GitHubUsername: RayZhang

      - username: Jarvis Liu
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/Jarvis.Liu@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/Jarvis.Liu@partner.bmwgroup.com
        QNumber: qxz3z5m
        Email: Jarvis.Liu@partner.bmwgroup.com
        GitHubUsername: JarvisLiu

      - username: Satyajeet Panigrahi
        GitHubRole: maintainer
        AWSArn: arn:aws:sts::111802884793:assumed-role/sso/satyajeet.panigrahi@partner.bmwgroup.com
        AWSArn-cn: arn:aws-cn:sts::265795087340:assumed-role/sso/satyajeet.panigrahi@partner.bmwgroup.com
        QNumber: qxz54tx
        Email: satyajeet.panigrahi@partner.bmwgroup.com
        GitHubUsername: satyajeet-panigrahi

  - team_name: "MRP"
    team_description: "MRP"
    users:
      - username: Johannes Lechner
        GitHubRole: maintainer
        QNumber: qxt9129
        Email: johannes.lechner@partner.bmwgroup.com

      - username: Daniel Para
        GitHubRole: maintainer
        QNumber: qxz10mf
        Email: daniel.para@partner.bmw.de

      - username: Grzegorz Jozwiak
        GitHubRole: maintainer
        QNumber: qxz2qii
        Email: grzegorz.gj.jozwiak@partner.bmw.de

      - username: Michal Makowski
        GitHubRole: maintainer
        QNumber: qxz4jis
        Email: michal.ma.makowski@partner.bmwgroup.com

accounts:
  cawe-admin:
    name: "CAWE Admin"
    row:
      prd: "831308554080"
    cn:
      e2e: "096149471542"

  cawe-advanced:
    name: "CAWE Advanced"
    row:
      dev: "092228957173"
      int: "500643607194"
      prd: "810674048896"
      sbox1: "992382369495"
      sbox2: "533267188729"
      sbox3: "058264387097"
    cn:
      test: "090973320140"
      int: "090974794329"
      prd: "090975101271"

  cawe-transit:
    name: "CAWE Transit (Default)"
    row:
      dev: "932595925475"
      int: "565128768560"
      prd: "088012017805"

  cawe-orbit:
    name: "CAWE Monitoring"
    int: "051351247033"
    prd: "641068916226"
