apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
data:
  config.yml: |
    modules:
      http_generic:
        prober: http
        timeout: 5s
        http:
          method: GET
          preferred_ip_protocol: "ip4"
          fail_if_ssl: false
          tls_config:
            insecure_skip_verify: true
      http_not_found:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [404]
          method: GET
          fail_if_ssl: false
          tls_config:
            insecure_skip_verify: true
          headers:
            Content-Type: "application/json"
      http_forbidden:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [403,401]
          method: GET
          tls_config:
            insecure_skip_verify: true
          fail_if_ssl: false
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: "ip4"
      http_post_2xx:
        prober: http
        http:
          method: POST
      tcp_connect:
        prober: tcp
        tcp:
          preferred_ip_protocol: "ip4"
          tls_config:
            insecure_skip_verify: true
      pop3s_banner:
        prober: tcp
        tcp:
          query_response:
          - expect: "^+OK"
          tls: true
          tls_config:
            insecure_skip_verify: false
      grpc:
        prober: grpc
        grpc:
          tls: true
          preferred_ip_protocol: "ip4"
      grpc_plain:
        prober: grpc
        grpc:
          tls: false
          service: "service1"
      ssh_banner:
        prober: tcp
        tcp:
          query_response:
          - expect: "^SSH-2.0-"
          - send: "SSH-2.0-blackbox-ssh-check"
      irc_banner:
        prober: tcp
        tcp:
          query_response:
          - send: "NICK prober"
          - send: "USER prober prober prober :prober"
          - expect: "PING :([^ ]+)"
            send: "PONG ${1}"
          - expect: "^:[^ ]+ 001"
      icmp:
        prober: icmp
      icmp_ttl5:
        prober: icmp
        timeout: 5s
        icmp:
          ttl: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox
  labels:
    app: blackbox
spec:
  replicas: {{ .Values.blackbox.replicas | default 1 }}
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
        - name: blackbox
          image: prom/blackbox-exporter:v0.24.0
          volumeMounts:
            - name: config-volume
              mountPath: /etc/blackbox_exporter
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL   
          resources:
            requests:
              cpu: 0.05
              memory: 128Mi
            limits:
              memory: 256Mi         
      volumes:
        - name: config-volume
          configMap:
            name: blackbox-config          
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox

spec:
  selector:
    app: blackbox
  ports:
  - port: 9115
    protocol: TCP
    targetPort: 9115
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: blackbox-pdb
  labels:
    app: blackbox
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: blackbox
    