apiVersion: v1
kind: ServiceAccount
metadata:
  name: cawe-monitoring-exporter-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.EKSAccountId }}:role/cawe/cawe-monitoring-exporter-role"
