apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cawe-monitoring-orbit-secret-store
    kind: SecretStore
  target:
    name: grafana-{{ .Values.environment }}-keycloak-client-secret
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: /cawe/cawe-monitoring/grafana-{{ .Values.environment }}-keycloak
