apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ""
    kubernetes.io/ingress.class: private-nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
       rewrite ^/insert/0/prometheus/api/(.*) /api/$1 break;
       rewrite ^/insert/multitenant/prometheus/api/(.*) /api/$1 break;
  name: victoria-metrics-ingest
  namespace: cawe-monitoring
spec:
  tls:
    - hosts:
        - metrics-injest.{{ .Values.environment }}.eu-central-1.cawe.daytona.eu-central-1.aws.cloud.bmw
      secretName: cawe-victoria-ingress
  rules:
    - host: metrics-injest.{{ .Values.environment }}.eu-central-1.cawe.daytona.eu-central-1.aws.cloud.bmw
      http:
        paths:
          - backend:
              service:
                name: cawe-monitoring-victoria-metrics-agent
                port:
                  number: 8429
            path: /
            pathType: ImplementationSpecific
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  cawe-victoria-ingress
  namespace: cawe-monitoring
spec:
  secretName: cawe-victoria-ingress
  commonName: "{{ .Values.environment }}.{{ .Values.region }}.cawe.acme.bmw.com"
  subject:
    organizations:
      - Bayerische Motoren Werke AG
    organizationalUnits:
      - Daytona
    localities:
      - Munich
    provinces:
      - Bavaria
    countries:
      - DE
  dnsNames:
    - "{{ .Values.environment }}.{{ .Values.region }}.cawe.acme.bmw.com"
    - "metrics-injest.{{ .Values.environment }}.eu-central-1.cawe.daytona.eu-central-1.aws.cloud.bmw"
  issuerRef:
    name: bmw-ca
    kind: ClusterIssuer