apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-grafana-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cawe-monitoring-orbit-secret-store
    kind: SecretStore
  target:
    name: postgresql-grafana-secret-{{ .Values.environment }}
    creationPolicy: Owner
  data:
    - secretKey: adminPassword
      remoteRef:
        key: /cawe/cawe-monitoring/postgresql-grafana-secret-{{ .Values.environment }}
        name: adminPassword
        property: adminPassword

    - secretKey: userPassword
      remoteRef:
        key: /cawe/cawe-monitoring/postgresql-grafana-secret-{{ .Values.environment }}
        name: userPassword
        property: userPassword
