{
 "title": "JAWS - KPI Over Time",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "filter", "label": "filters" },
   { "name": "filter2", "label": "filter" }
  ]
 },
 "panels": [
  { "title": "Per team", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate (%) - Over Time",
   "type": "timeseries",
   "description": "It shows the build success rate (%) based on selected Customer and timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(jenkins_runs_success/jenkins_runs_total) * 100",
     "legendFormat": "Success Rate {{jaws_instance}} (%)"
    }
   ]
  },
  {
   "title": "Build Time in hours (Daily) - Over Time",
   "type": "timeseries",
   "description": "It shows the total build time (daily) based on selected Customer and timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    { "expr": "daily_total_duration_seconds", "legendFormat": "{{jaws_instance}}" }
   ]
  },
  {
   "title": "Total Jaws Agents (Daily) - Over Time",
   "type": "timeseries",
   "description": "It shows the build success rate (%) based on selected Customer and timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "jenkins_node_count_value", "legendFormat": "JAWS Agents {{jaws_instance}}" }
   ]
  },
  {
   "title": "Total Runs Usage (Daily) per Status - Over Time",
   "type": "timeseries",
   "description": "It shows the total build time (daily) per status based on selected Customer and timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "increase(jenkins_runs_success)", "legendFormat": "{{jaws_instance}} - success" },
    { "expr": "increase(jenkins_runs_failure)", "legendFormat": "{{jaws_instance}} - failure" },
    { "expr": "increase(jenkins_runs_aborted)", "legendFormat": "{{jaws_instance}} - cancelled" }
   ]
  },
  { "title": "Overall Product Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Jaws Agents (Daily) - Over Time",
   "type": "timeseries",
   "description": "It shows the build success rate (%) based on selected timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(jenkins_node_count_value)", "legendFormat": "JAWS Agents" },
    {
     "expr": "sum(jenkins_executor_count_value)",
     "legendFormat": "JAWS executors"
    }
   ]
  },
  {
   "title": "Build Time in hours (Daily) - Over Time",
   "type": "timeseries",
   "description": "It shows the total build time (daily) based on selected timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "sum by (environment) (daily_total_duration_seconds{environment !=\"emea-dev\", environment !=\"emea-test\", environment !=\"china-dev\", environment !=\"china-test\"} )",
     "legendFormat": "{{environment}} Build Time (Daily)"
    }
   ]
  },
  {
   "title": "Success Rate (%) - Over Time",
   "type": "timeseries",
   "description": "It shows the build success rate (%) based on selected timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jenkins_runs_success/jenkins_runs_total * 100) / count(jenkins_runs_success)",
     "legendFormat": "Success Rate (%) {{jaws_instance}}"
    }
   ]
  },
  {
   "title": "Total Runs Usage (Daily) per status- Over Time",
   "type": "timeseries",
   "description": "It shows the total build time (daily) per status based on selected timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(jenkins_runs_success))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(increase(jenkins_runs_failure))",
     "legendFormat": "failures"
    },
    {
     "expr": "sum(increase(jenkins_runs_aborted))",
     "legendFormat": "cancelled"
    }
   ]
  }
 ]
}