{
 "title": "AWS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Lambda concurrent executions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(aws_lambda_concurrent_executions_sum{})",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Lambda duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(aws_lambda_duration_sum{})",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Total cloudwatch requesta",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (cloudwatch_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages sqs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_sum{}",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Lambda errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "targets": [
    { "expr": "rate(aws_lambda_errors_sum{})", "legendFormat": "{{function_name}}" }
   ]
  },
  {
   "title": "Lambda throttles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "rate(aws_lambda_throttles_sum{})",
     "legendFormat": "{{function_name}}"
    }
   ]
  }
 ]
}