{
 "title": "Orbit Spaceship - Endpoints Prober",
 "description": "Blackbox exporter HTTP&TCP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)\n"
    }
   },
   {
    "name": "job",
    "label": "Account",
    "query": {
     "query": "label_values(probe_success, job)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", instance=~\"$instance\",job=\"$job\"} > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()) / 3600 / 24\n\n\n\n\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", instance=~\"$instance\"} > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\",job=\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Probe Phases Duration",
     "type": "timeseries",
     "description": "Duration of http request by phase, summed over all redirects",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\",job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}