{
 "title": "Costs",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "org",
    "label": "org",
    "query": {
     "query": "label_values(cawe_metadata_info{}, github_org)\n"
    }
   },
   {
    "name": "repo",
    "label": "repo",
    "query": {
     "query": "label_values(customer_costs{org=\"$org\"}, repo)\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Per Organisation Costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Org Cost detailed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "customer_costs{org=~\"$org\", repo=~\"$repo\"}",
     "legendFormat": "{{repo}} - {{label}}"
    }
   ]
  },
  {
   "title": "Cost per month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(customer_costs{org=\"$org\", repo=~\"$repo\"})",
     "legendFormat": "{{repo}} - {{label}}"
    }
   ]
  },
  { "title": "Overall Costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last average cost per minute",
   "type": "stat",
   "description": "Average cost per minute",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(label_cost)", "legendFormat": "Average cost per minute" }
   ]
  },
  {
   "title": "Average cost per minute",
   "type": "stat",
   "description": "Average cost per minute",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(label_cost)", "legendFormat": "Average cost per minute" }
   ]
  },
  {
   "title": "Label cost per minute",
   "type": "state-timeline",
   "description": "This shows the Label cost per minute calculated for the day n-1. Non EC2 costs are included",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "label_cost{job=\"runner-cost-exporter\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Last label cost per minute",
   "type": "bargauge",
   "description": "This shows the Label cost per minute calculated for the day n-1. Non EC2 costs are included",
   "gridPos": { "h": 24, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "label_cost", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "Label cost per minute",
   "type": "timeseries",
   "description": "This shows the Label cost per minute calculated for the day n-1. Non EC2 costs are included",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "label_cost{job=\"runner-cost-exporter\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Non Ec2 cost per minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "non_ec2_costs_total{}", "legendFormat": "Non Ec2 cost" },
    { "expr": "non_ec2_costs_minute{}", "legendFormat": "Non Ec2 cost per minute" }
   ]
  }
 ]
}