{
 "title": "General Usage",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "org",
    "label": "org",
    "query": {
     "query": "label_values(cawe_metadata_info{job=~\"$job\"}, github_org)\n"
    }
   },
   { "name": "job", "label": "job", "query": "macos,linux" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workflows - Top 10 Organisations",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(organization_login) (workflow_job{workflow_job_status=~\"completed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Completed Jobs",
   "type": "stat",
   "description": "It shows the total completed jobs by customers in a defined timeframe.",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(workflow_job{workflow_job_status=~\"completed\"}[$__range])",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Overall - Success Rate",
   "type": "piechart",
   "description": "It shows the overall rate of Jobs executed in a defined timeframe.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count_values by(workflow_job_conclusion) (\"count\", workflow_job{workflow_job_conclusion!=\"null\", workflow_job_status=\"completed\"})",
     "legendFormat": "{{workflow_job_conclusion}}"
    }
   ]
  },
  {
   "title": "Overall - Average Queue Time",
   "type": "gauge",
   "description": "it shows an overall average queue time to get runners provisioned for customers.\n\nWe consider healthy keeping it under 30 seconds.",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MEDIAN(job_queued_time{}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall - Completion Time",
   "type": "stat",
   "description": "It shows the median job completion time for Linux runners in a defined timeframe.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "MEDIAN(job_in_progress_time{}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflows - Execution per Organisation",
     "type": "state-timeline",
     "description": "It shows the timeline of completed workflows per customer (GitHub Organisation) in a defined timeframe.",
     "gridPos": { "h": 28, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count by(organization_login) (workflow_job{workflow_job_status=~\"completed\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Time and Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average - Usage per Label",
     "type": "bargauge",
     "description": "It shows the mean usage per label for all customers in a defined timeframe.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count_values by(github_labels) (\"count\", sum by(instance, github_labels) (cawe_metadata_info{github_labels!=\"\"}))",
       "legendFormat": "{{github_labels}}"
      }
     ]
    },
    {
     "title": "Average - Queue Time per Label",
     "type": "bargauge",
     "description": "it shows an average queue time to get runners provisioned for customers per label (warm pools).\n\nWe consider healthy keeping it under 30 seconds.\n\nIf any label presents average time frequently over 30 seconds, we should consider review the Pool  dimensioning.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "MEDIAN(job_queued_time{}[$__range]) by (label)",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Linux - Average - Queued Time Over Time",
     "type": "timeseries",
     "description": "It shows the average queued time to provision a runner for Linux Customers in a defined timeframe.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "MEDIAN(job_queued_time{os=\"linux\"})",
       "legendFormat": "Current"
      }
     ]
    },
    {
     "title": "macOS - Average - Queued Time Over Time",
     "type": "timeseries",
     "description": "It shows the average queued time to provision a runner for macOS Customers in a defined timeframe.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "MEDIAN(job_queued_time{os=\"macos\"})",
       "legendFormat": "Current"
      }
     ]
    }
   ]
  },
  { "title": "Linux Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Overall Usage per Label",
   "type": "timeseries",
   "description": "It shows the timeline of runners provisioned for jobs executed by customers in a defined timeframe.",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count_values by(github_labels) (\"count\", sum by(instance, github_labels) (cawe_metadata_info{job=\"linux\",github_labels!=\"\"}))",
     "legendFormat": "{{github_labels}}"
    }
   ]
  },
  {
   "title": "Linux - Queued Time",
   "type": "stat",
   "description": "It shows the median queued time to provision a runner for Linux Customers in a defined timeframe.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "MEDIAN(job_queued_time{os=\"linux\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux - Completion Time",
   "type": "stat",
   "description": "It shows the median job completion time for Linux runners in a defined timeframe.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "MEDIAN(job_in_progress_time{os=\"linux\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "macOS Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "macOS - Availability x Usage",
   "type": "timeseries",
   "description": "It shows the availability versus in use for macOS runners in a defined timeframe.",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(virt_process_count_int{job=\"macos_hypervisor\"})) ",
     "legendFormat": "In Use"
    },
    {
     "expr": "(count(go_info{job=\"macos_hypervisor\"}) * 2)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "macOS - Queued Time",
   "type": "stat",
   "description": "It shows the median queued time to provision a runner for macOS Customers in a defined timeframe.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "MEDIAN(job_queued_time{os=\"macos\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "macOS - Runners Allocation",
   "type": "bargauge",
   "description": "It shows the allocation of macOS runner on the available hosts.",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "virt_process_count_int{job=\"macos_hypervisor\"}[$__range]",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "macOS - Completion time",
   "type": "stat",
   "description": "It shows the median job completion time for macOS runners in a defined timeframe.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "MEDIAN(job_in_progress_time{os=\"macos\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "macOS - Runners allocation over time",
   "type": "state-timeline",
   "description": "It shows the allocation of macOS runner on the available hosts.",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "virt_process_count_int{job=\"macos_hypervisor\"}[$__range]",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}