{
 "title": "Orbit Spaceship - Over Time",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "macos,linux" },
   {
    "name": "org",
    "label": "org",
    "query": {
     "query": "label_values(cawe_metadata_info{job=~\"$job\"}, github_org)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Per Organisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success Rate (%)",
     "type": "timeseries",
     "description": "It shows the build success rate (%)(daily) based on selected Customer and timeframe.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "###### Success Rate Over Time\n\n((count by(count) (last_over_time(workflow_job{organization_login=\"$org\", workflow_job_status=\"completed\", workflow_job_conclusion=\"success\", os=\"$job\"}[$__interval])))\n/\n(count by(count) (last_over_time(workflow_job{organization_login=\"$org\", workflow_job_status=\"completed\", workflow_job_conclusion=\"success\", os=\"$job\"}[$__interval]))\n+ \ncount by(count) (last_over_time(workflow_job{organization_login=\"$org\", workflow_job_status=\"completed\", workflow_job_conclusion=\"failure\", os=\"$job\"}[$__interval]))\n+ \ncount by(count) (last_over_time(workflow_job{organization_login=\"$org\", workflow_job_status=\"completed\", workflow_job_conclusion=\"cancelled\", os=\"$job\"}[$__interval])))) * 100",
       "legendFormat": "Success Rate (%)"
      }
     ]
    },
    {
     "title": "Build Time in hours (Daily)",
     "type": "timeseries",
     "description": "It shows the total build time (daily) based on selected Customer and timeframe.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "targets": [
      {
       "expr": "sum(job_in_progress_time{os=\"$job\", organization_login=\"$org\"})",
       "legendFormat": "Build Time (Daily)"
      }
     ]
    },
    {
     "title": "Total Runners (Daily)",
     "type": "timeseries",
     "description": "It shows the total number of runners (daily) used based on selected Customer and timeframe.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(count by(count) (last_over_time(workflow_job{organization_login=\"$org\", workflow_job_status=\"completed\", workflow_job_conclusion=\"success\", os=\"$job\"}[$__interval]))\n+ \ncount by(count) (last_over_time(workflow_job{organization_login=\"$org\", workflow_job_status=\"completed\", workflow_job_conclusion=\"failure\", os=\"$job\"}[$__interval]))\n+ \ncount by(count) (last_over_time(workflow_job{organization_login=\"$org\", workflow_job_status=\"completed\", workflow_job_conclusion=\"cancelled\", os=\"$job\"}[$__interval])))",
       "legendFormat": "{{workflow_job_conclusion}}"
      }
     ]
    },
    {
     "title": "Total Runners Usage (Daily) per Status",
     "type": "timeseries",
     "description": "It shows the total of runners used (daily) per status based on selected Customer and timeframe.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "(count by(workflow_job_conclusion) (sum_over_time(workflow_job{workflow_job_conclusion!=\"null\", organization_login=\"$org\", workflow_job_status=\"completed\", os=\"$job\"}[$__interval])))",
       "legendFormat": "{{workflow_job_conclusion}}"
      }
     ]
    }
   ]
  },
  { "title": "Overall Product Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Success Rate (%)",
   "type": "timeseries",
   "description": "It shows the build success rate (%)(daily) based on selected timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "###### Success Rate Over Time\n\n((count by(count) (last_over_time(workflow_job{workflow_job_status=\"completed\", workflow_job_conclusion=\"success\", os=\"$job\"}[$__interval])))\n/\n(count by(count) (last_over_time(workflow_job{workflow_job_status=\"completed\", workflow_job_conclusion=\"success\", os=\"$job\"}[$__interval]))\n+ \ncount by(count) (last_over_time(workflow_job{workflow_job_status=\"completed\", workflow_job_conclusion=\"failure\", os=\"$job\"}[$__interval]))\n+ \ncount by(count) (last_over_time(workflow_job{workflow_job_status=\"completed\", workflow_job_conclusion=\"cancelled\", os=\"$job\"}[$__interval])))) * 100",
     "legendFormat": "Success Rate (%)"
    }
   ]
  },
  {
   "title": "Build Time in hours (Daily)",
   "type": "timeseries",
   "description": "It shows the total build time (daily) based on selected timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "sum(job_in_progress_time{os=\"$job\"})",
     "legendFormat": "Build Time (Daily)"
    }
   ]
  },
  {
   "title": "Total Runners (Daily)",
   "type": "timeseries",
   "description": "It shows the total number of runners (daily) used based on selected timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(count by(count) (last_over_time(workflow_job{workflow_job_status=\"completed\", workflow_job_conclusion=\"success\", os=\"$job\"}[$__interval]))\n+ \ncount by(count) (last_over_time(workflow_job{workflow_job_status=\"completed\", workflow_job_conclusion=\"failure\", os=\"$job\"}[$__interval]))\n+ \ncount by(count) (last_over_time(workflow_job{workflow_job_status=\"completed\", workflow_job_conclusion=\"cancelled\", os=\"$job\"}[$__interval])))",
     "legendFormat": "{{workflow_job_conclusion}}"
    }
   ]
  },
  {
   "title": "Total Runners Usage (Daily) per Status",
   "type": "timeseries",
   "description": "It shows the total of runners used (daily) per status based on selected timeframe.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(count by(workflow_job_conclusion) (sum_over_time(workflow_job{workflow_job_conclusion!=\"null\", workflow_job_status=\"completed\", os=\"$job\"}[$__interval])))",
     "legendFormat": "{{workflow_job_conclusion}}"
    }
   ]
  }
 ]
}