{
 "title": "Spaceship - Org x Workflows",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "org",
    "label": "org",
    "query": {
     "query": "label_values(workflow_run{}, organization_login)\n"
    }
   },
   {
    "name": "workflow",
    "label": "workflow",
    "query": {
     "query": "label_values(cawe_workflow_duration{}, workflow_name)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Organization usage ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time(sum by (organization) (cawe_workflow_duration{workflow_name=~\"$workflow\", organization=~\"$org\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(job_status) (sum_over_time(cawe_workflow_duration{workflow_name=~\"$workflow\", organization=~\"$org\"}[$__interval]))",
     "legendFormat": "{{job_status}}"
    }
   ]
  },
  {
   "title": "Workflow duration",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(workflow_name) (cawe_workflow_duration{workflow_name=~\"$workflow\", organization=~\"$org\"})",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Workflow usage",
   "type": "stat",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time(sum by (workflow_name) (cawe_workflow_duration{workflow_name=~\"$workflow\", organization=~\"$org\"}[$__interval]))",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "General ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Run Analytics",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "count by(organization_login, repository_full_name, workflow_run_name) (\"count\", workflow_run{organization_login=\"$org\", workflow_run_status=\"completed\"}[$__range])",
       "legendFormat": "Runs"
      },
      {
       "expr": "count by(organization_login, repository_full_name, workflow_run_name) (\"count\", workflow_run{organization_login=\"$org\", workflow_run_status=\"completed\",workflow_run_conclusion=\"failure\"}[$__range])",
       "legendFormat": "Fails"
      },
      {
       "expr": "((count by(organization_login, repository_full_name, workflow_run_name) (\"count\", workflow_run{organization_login=\"$org\", workflow_run_status=\"completed\"}[$__range]) - count by(organization_login, repository_full_name, workflow_run_name) (\"count\", workflow_run{organization_login=\"$org\", workflow_run_status=\"completed\",workflow_run_conclusion=\"failure\"}[$__range])) * 100) / count by(organization_login, repository_full_name, workflow_run_name) (\"count\", workflow_run{organization_login=\"$org\", workflow_run_status=\"completed\"}[$__range])",
       "legendFormat": "Fails"
      }
     ]
    },
    {
     "title": "Workflow Label Usage",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "((label_replace(workflow_run{organization_login=\"$org\", workflow_run_status=\"completed\"}, \"workflow_job_run_id\", \"$1\", \"instance\", \"(.+)\"))\n    * on(workflow_job_run_id) group_left(workflow_job_labels)\n(workflow_job))[$__range]",
       "legendFormat": "{{repository_full_name}} {{workflow_run_name}} {{workflow_job_labels}}"
      }
     ]
    }
   ]
  }
 ]
}