{
 "title": "Orbit Spaceship - Analytical for Teams",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "macos,linux" },
   {
    "name": "org",
    "label": "org",
    "query": {
     "query": "label_values(workflow_job{os=\"$job\"}, organization_login)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall Usage per Customer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$org - Labels Over Time",
   "type": "timeseries",
   "description": "It shows the timeline of jobs executed by a customer in a defined timeframe.",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 1 },
   "repeat": "org",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_values by(github_labels) (\"count\", sum by(instance, github_labels) (cawe_metadata_info{job=\"$job\", github_org=\"$org\"}))",
     "legendFormat": "{{github_labels}}"
    }
   ]
  },
  {
   "title": "$org - Build Time",
   "type": "stat",
   "description": "It shows the total time of builds done by a customer in a defined timeframe.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "repeat": "org",
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(job_in_progress_time{os=\"$job\", organization_login=\"$org\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$org - Success rate",
   "type": "piechart",
   "description": "It shows the rate of Jobs executed by a customer in a defined timeframe.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "repeat": "org",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_values by(workflow_job_conclusion) (\"count\", last_over_time(workflow_job{workflow_job_conclusion!=\"null\", organization_login=\"$org\", workflow_job_status=\"completed\", os=\"$job\"}[$__interval]))",
     "legendFormat": "{{workflow_job_conclusion}}"
    }
   ]
  },
  {
   "title": "Overall Queue Time per Customer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "$org - Queued Time Over Time per Label ",
   "type": "timeseries",
   "description": "It shows the average queued time per Label to provision runners for Customers in a defined timeframe.",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 12 },
   "repeat": "org",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "AVG(job_queued_time{organization_login=\"$org\", os=\"$job\"}[$__range]) by (arch,os,purpose,size)",
     "legendFormat": "cawe-{{arch}}-{{purpose}}-{{size}}"
    }
   ]
  },
  {
   "title": "Overall - Average Queue Time",
   "type": "gauge",
   "description": "it shows an overall average queue time per OS to get runners provisioned for customers.\n\nWe consider healthy keeping it under 30 seconds.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "repeat": "org",
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AVG(job_queued_time{organization_login=\"$org\", os=\"$job\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}