{
 "title": "General Usage CN",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "org",
    "label": "org",
    "query": {
     "query": "label_values(cawe_metadata_info{job=~\"$job\"}, github_org)\n"
    }
   },
   { "name": "job", "label": "job", "query": "macos,linux" }
  ]
 },
 "panels": [
  {
   "title": "Linux - Queued Time",
   "type": "stat",
   "description": "It shows the median queued time to provision a runner for Linux Customers in a defined timeframe.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "MEDIAN(job_queued_time{os=\"linux\",label=~\".*-cn\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Completed Jobs",
   "type": "stat",
   "description": "It shows the total completed jobs by customers in a defined timeframe.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(workflow_job{workflow_job_status=~\"completed\",workflow_job_labels=~\".*-cn\"}[$__range])",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Linux - Average - Queued Time Over Time",
   "type": "barchart",
   "description": "It shows the average queued time to provision a runner for Linux Customers in a defined timeframe.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "MEDIAN(job_queued_time{os=\"linux\", label=~\".*-cn\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Overall Usage per Label",
   "type": "timeseries",
   "description": "It shows the timeline of runners provisioned for jobs executed by customers in a defined timeframe.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count_values by(github_labels) (\"count\", sum by(instance, github_labels) (cawe_metadata_info{aws_region=\"cn-north-1\", github_labels!=\"\"}))",
     "legendFormat": "{{github_labels}}"
    }
   ]
  }
 ]
}