{
 "title": "General Usage",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "org",
    "label": "org",
    "query": {
     "query": "label_values(cawe_metadata_info{job=~\"$job\"}, github_org)\n"
    }
   },
   { "name": "job", "label": "job", "query": "macos,linux" }
  ]
 },
 "panels": [
  {
   "title": "Linux - Queued Time",
   "type": "stat",
   "description": "It shows the median queued time to provision a runner for Linux Customers in a defined timeframe.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "MEDIAN(job_queued_time{os=\"linux\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Completed Jobs",
   "type": "stat",
   "description": "It shows the total completed jobs by customers in a defined timeframe.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(workflow_job{workflow_job_status=~\"completed\"}[$__range])",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "macOS - Queued Time",
   "type": "stat",
   "description": "It shows the median queued time to provision a runner for macOS Customers in a defined timeframe.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "MEDIAN(job_queued_time{os=\"macos\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux - Average - Queued Time Over Time",
   "type": "timeseries",
   "description": "It shows the average queued time to provision a runner for Linux Customers in a defined timeframe.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "MEDIAN(job_queued_time{os=\"linux\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "macOS - Average - Queued Time Over Time",
   "type": "timeseries",
   "description": "It shows the average queued time to provision a runner for macOS Customers in a defined timeframe.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "MEDIAN(job_queued_time{os=\"macos\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Overall Usage per Label",
   "type": "timeseries",
   "description": "It shows the timeline of runners provisioned for jobs executed by customers in a defined timeframe.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count_values by(github_labels) (\"count\", sum by(instance, github_labels) (cawe_metadata_info{job=\"linux\",github_labels!=\"\"}))",
     "legendFormat": "{{github_labels}}"
    }
   ]
  },
  {
   "title": "macOS - Availability x Usage",
   "type": "timeseries",
   "description": "It shows the availability versus in use for macOS runners in a defined timeframe.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(virt_process_count_int{job=\"macos_hypervisor\"})) ",
     "legendFormat": "In Use"
    },
    {
     "expr": "(count(go_info{job=\"macos_hypervisor\"}) * 2)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}