name: Plan accounts
description: Plan accounts

inputs:
  AWS_REGION:
    required: true
    description: "AWS region"
    default: "eu-central-1"

  TF_VERSION:
    description: "Terraform Version"
    required: true

  NODE_VERSION:
    description: "NodeJS Version to be configured"
    required: true

  TF_WORKSPACE:
    description: "Name of the Terraform Workspace"
    required: true

runs:
  using: "composite"
  steps:
    - name: Node.JS - Setup
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}

    - name: Terraform - Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.2"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::831308554080:role/cawe/cawe-developer
        role-skip-session-tagging: true
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Terraform - Init
      id: init
      shell: bash
      run: terraform init --upgrade
      working-directory: ${{ inputs.TF_WORKSPACE }}

    - name: Print Workspace
      shell: bash
      run: echo ${{inputs.TF_WORKSPACE }} | sed 's/./& /g'

    - name: Terraform - Select Workspace
      id: workspace
      shell: bash
      working-directory: ${{ inputs.TF_WORKSPACE }}
      run: terraform workspace select ${{ inputs.TF_WORKSPACE }}

    - name: Terraform - Validate
      id: validate
      shell: bash
      run: terraform validate

    - name: Terraform - Plan
      id: apply
      shell: bash
      working-directory: ${{ inputs.TF_WORKSPACE }}
      run: terraform plan -out=../plan-${{ inputs.TF_WORKSPACE }}.tfplan -var-file inputs.tfvars

    - name: Upload terraform plan file
      uses: actions/upload-artifact@v3
      with:
        name: plan-${{ inputs.TF_WORKSPACE  }}.tfplan
        path: plan-${{ inputs.TF_WORKSPACE  }}.tfplan
