apiVersion: v2
name: cawe-monitoring
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: victoria-metrics-cluster
    version: 0.9.72
    repository: https://victoriametrics.github.io/helm-charts/
    alias: victoria-metrics

  - name: victoria-metrics-agent
    version: 0.9.2
    repository: https://victoriametrics.github.io/helm-charts/

  - name: victoria-metrics-alert
    version: 0.8.1
    repository: https://victoriametrics.github.io/helm-charts/

  - name: grafana
    version: 8.5.8
    repository: https://grafana.github.io/helm-charts/

  - name: postgresql
    version: 15.5.38
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql

  - name: loki
    version: 2.8.0
    repository: https://grafana.github.io/helm-charts/

  - name: alertmanager
    version: 1.13.1
    repository: https://prometheus-community.github.io/helm-charts
    alias: alertmanager
